# permissions for end users to view nonadminbackupstoragelocations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nonadminbackupstoragelocation-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: oadp-nac
    app.kubernetes.io/part-of: oadp-nac
    app.kubernetes.io/managed-by: kustomize
  name: nonadminbackupstoragelocation-viewer-role
rules:
- apiGroups:
  - oadp.openshift.io
  resources:
  - nonadminbackupstoragelocations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - oadp.openshift.io
  resources:
  - nonadminbackupstoragelocations/status
  verbs:
  - get
