# permissions for end users to edit nonadminbackupstoragelocations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: oadp-nac
    app.kubernetes.io/managed-by: kustomize
  name: nonadminbackupstoragelocation-editor-role
rules:
- apiGroups:
  - oadp.openshift.io
  resources:
  - nonadminbackupstoragelocations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oadp.openshift.io
  resources:
  - nonadminbackupstoragelocations/status
  verbs:
  - get
