apiVersion: oadp.openshift.io/v1alpha1
kind: NonAdminBackupStorageLocation
metadata:
  labels:
    app.kubernetes.io/name: nonadminbackupstoragelocation
    app.kubernetes.io/instance: nonadminbackupstoragelocation-sample
    app.kubernetes.io/part-of: oadp-nac
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: oadp-nac
  name: nonadminbackupstoragelocation-sample
spec:
  backupStorageLocationSpec:
    config:
      checksumAlgorithm: ''
      region: eu-central-1
    credential:
      key: default
      name: cloud-credentials
    objectStorage:
      bucket: my-bucket
      prefix: nac-test
    provider: aws
