//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/vmware-tanzu/velero/pkg/apis/velero/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataMoverDataDownloads) DeepCopyInto(out *DataMoverDataDownloads) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataMoverDataDownloads.
func (in *DataMoverDataDownloads) DeepCopy() *DataMoverDataDownloads {
	if in == nil {
		return nil
	}
	out := new(DataMoverDataDownloads)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataMoverDataUploads) DeepCopyInto(out *DataMoverDataUploads) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataMoverDataUploads.
func (in *DataMoverDataUploads) DeepCopy() *DataMoverDataUploads {
	if in == nil {
		return nil
	}
	out := new(DataMoverDataUploads)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileSystemPodVolumeBackups) DeepCopyInto(out *FileSystemPodVolumeBackups) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileSystemPodVolumeBackups.
func (in *FileSystemPodVolumeBackups) DeepCopy() *FileSystemPodVolumeBackups {
	if in == nil {
		return nil
	}
	out := new(FileSystemPodVolumeBackups)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileSystemPodVolumeRestores) DeepCopyInto(out *FileSystemPodVolumeRestores) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileSystemPodVolumeRestores.
func (in *FileSystemPodVolumeRestores) DeepCopy() *FileSystemPodVolumeRestores {
	if in == nil {
		return nil
	}
	out := new(FileSystemPodVolumeRestores)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminBackup) DeepCopyInto(out *NonAdminBackup) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminBackup.
func (in *NonAdminBackup) DeepCopy() *NonAdminBackup {
	if in == nil {
		return nil
	}
	out := new(NonAdminBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NonAdminBackup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminBackupList) DeepCopyInto(out *NonAdminBackupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NonAdminBackup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminBackupList.
func (in *NonAdminBackupList) DeepCopy() *NonAdminBackupList {
	if in == nil {
		return nil
	}
	out := new(NonAdminBackupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NonAdminBackupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminBackupSpec) DeepCopyInto(out *NonAdminBackupSpec) {
	*out = *in
	if in.BackupSpec != nil {
		in, out := &in.BackupSpec, &out.BackupSpec
		*out = new(v1.BackupSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminBackupSpec.
func (in *NonAdminBackupSpec) DeepCopy() *NonAdminBackupSpec {
	if in == nil {
		return nil
	}
	out := new(NonAdminBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminBackupStatus) DeepCopyInto(out *NonAdminBackupStatus) {
	*out = *in
	if in.VeleroBackup != nil {
		in, out := &in.VeleroBackup, &out.VeleroBackup
		*out = new(VeleroBackup)
		(*in).DeepCopyInto(*out)
	}
	if in.VeleroDeleteBackupRequest != nil {
		in, out := &in.VeleroDeleteBackupRequest, &out.VeleroDeleteBackupRequest
		*out = new(VeleroDeleteBackupRequest)
		(*in).DeepCopyInto(*out)
	}
	if in.DataMoverDataUploads != nil {
		in, out := &in.DataMoverDataUploads, &out.DataMoverDataUploads
		*out = new(DataMoverDataUploads)
		**out = **in
	}
	if in.FileSystemPodVolumeBackups != nil {
		in, out := &in.FileSystemPodVolumeBackups, &out.FileSystemPodVolumeBackups
		*out = new(FileSystemPodVolumeBackups)
		**out = **in
	}
	if in.QueueInfo != nil {
		in, out := &in.QueueInfo, &out.QueueInfo
		*out = new(QueueInfo)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminBackupStatus.
func (in *NonAdminBackupStatus) DeepCopy() *NonAdminBackupStatus {
	if in == nil {
		return nil
	}
	out := new(NonAdminBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminBackupStorageLocation) DeepCopyInto(out *NonAdminBackupStorageLocation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminBackupStorageLocation.
func (in *NonAdminBackupStorageLocation) DeepCopy() *NonAdminBackupStorageLocation {
	if in == nil {
		return nil
	}
	out := new(NonAdminBackupStorageLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NonAdminBackupStorageLocation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminBackupStorageLocationList) DeepCopyInto(out *NonAdminBackupStorageLocationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NonAdminBackupStorageLocation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminBackupStorageLocationList.
func (in *NonAdminBackupStorageLocationList) DeepCopy() *NonAdminBackupStorageLocationList {
	if in == nil {
		return nil
	}
	out := new(NonAdminBackupStorageLocationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NonAdminBackupStorageLocationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminBackupStorageLocationRequest) DeepCopyInto(out *NonAdminBackupStorageLocationRequest) {
	*out = *in
	in.Status.DeepCopyInto(&out.Status)
	out.Spec = in.Spec
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminBackupStorageLocationRequest.
func (in *NonAdminBackupStorageLocationRequest) DeepCopy() *NonAdminBackupStorageLocationRequest {
	if in == nil {
		return nil
	}
	out := new(NonAdminBackupStorageLocationRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NonAdminBackupStorageLocationRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminBackupStorageLocationRequestList) DeepCopyInto(out *NonAdminBackupStorageLocationRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NonAdminBackupStorageLocationRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminBackupStorageLocationRequestList.
func (in *NonAdminBackupStorageLocationRequestList) DeepCopy() *NonAdminBackupStorageLocationRequestList {
	if in == nil {
		return nil
	}
	out := new(NonAdminBackupStorageLocationRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NonAdminBackupStorageLocationRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminBackupStorageLocationRequestSpec) DeepCopyInto(out *NonAdminBackupStorageLocationRequestSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminBackupStorageLocationRequestSpec.
func (in *NonAdminBackupStorageLocationRequestSpec) DeepCopy() *NonAdminBackupStorageLocationRequestSpec {
	if in == nil {
		return nil
	}
	out := new(NonAdminBackupStorageLocationRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminBackupStorageLocationRequestStatus) DeepCopyInto(out *NonAdminBackupStorageLocationRequestStatus) {
	*out = *in
	if in.SourceNonAdminBSL != nil {
		in, out := &in.SourceNonAdminBSL, &out.SourceNonAdminBSL
		*out = new(SourceNonAdminBSL)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminBackupStorageLocationRequestStatus.
func (in *NonAdminBackupStorageLocationRequestStatus) DeepCopy() *NonAdminBackupStorageLocationRequestStatus {
	if in == nil {
		return nil
	}
	out := new(NonAdminBackupStorageLocationRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminBackupStorageLocationSpec) DeepCopyInto(out *NonAdminBackupStorageLocationSpec) {
	*out = *in
	if in.BackupStorageLocationSpec != nil {
		in, out := &in.BackupStorageLocationSpec, &out.BackupStorageLocationSpec
		*out = new(v1.BackupStorageLocationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminBackupStorageLocationSpec.
func (in *NonAdminBackupStorageLocationSpec) DeepCopy() *NonAdminBackupStorageLocationSpec {
	if in == nil {
		return nil
	}
	out := new(NonAdminBackupStorageLocationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminBackupStorageLocationStatus) DeepCopyInto(out *NonAdminBackupStorageLocationStatus) {
	*out = *in
	if in.VeleroBackupStorageLocation != nil {
		in, out := &in.VeleroBackupStorageLocation, &out.VeleroBackupStorageLocation
		*out = new(VeleroBackupStorageLocation)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminBackupStorageLocationStatus.
func (in *NonAdminBackupStorageLocationStatus) DeepCopy() *NonAdminBackupStorageLocationStatus {
	if in == nil {
		return nil
	}
	out := new(NonAdminBackupStorageLocationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminDownloadRequest) DeepCopyInto(out *NonAdminDownloadRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminDownloadRequest.
func (in *NonAdminDownloadRequest) DeepCopy() *NonAdminDownloadRequest {
	if in == nil {
		return nil
	}
	out := new(NonAdminDownloadRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NonAdminDownloadRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminDownloadRequestList) DeepCopyInto(out *NonAdminDownloadRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NonAdminDownloadRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminDownloadRequestList.
func (in *NonAdminDownloadRequestList) DeepCopy() *NonAdminDownloadRequestList {
	if in == nil {
		return nil
	}
	out := new(NonAdminDownloadRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NonAdminDownloadRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminDownloadRequestSpec) DeepCopyInto(out *NonAdminDownloadRequestSpec) {
	*out = *in
	out.Target = in.Target
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminDownloadRequestSpec.
func (in *NonAdminDownloadRequestSpec) DeepCopy() *NonAdminDownloadRequestSpec {
	if in == nil {
		return nil
	}
	out := new(NonAdminDownloadRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminDownloadRequestStatus) DeepCopyInto(out *NonAdminDownloadRequestStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminDownloadRequestStatus.
func (in *NonAdminDownloadRequestStatus) DeepCopy() *NonAdminDownloadRequestStatus {
	if in == nil {
		return nil
	}
	out := new(NonAdminDownloadRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminRestore) DeepCopyInto(out *NonAdminRestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminRestore.
func (in *NonAdminRestore) DeepCopy() *NonAdminRestore {
	if in == nil {
		return nil
	}
	out := new(NonAdminRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NonAdminRestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminRestoreList) DeepCopyInto(out *NonAdminRestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NonAdminRestore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminRestoreList.
func (in *NonAdminRestoreList) DeepCopy() *NonAdminRestoreList {
	if in == nil {
		return nil
	}
	out := new(NonAdminRestoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NonAdminRestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminRestoreSpec) DeepCopyInto(out *NonAdminRestoreSpec) {
	*out = *in
	if in.RestoreSpec != nil {
		in, out := &in.RestoreSpec, &out.RestoreSpec
		*out = new(v1.RestoreSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminRestoreSpec.
func (in *NonAdminRestoreSpec) DeepCopy() *NonAdminRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(NonAdminRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonAdminRestoreStatus) DeepCopyInto(out *NonAdminRestoreStatus) {
	*out = *in
	if in.VeleroRestore != nil {
		in, out := &in.VeleroRestore, &out.VeleroRestore
		*out = new(VeleroRestore)
		(*in).DeepCopyInto(*out)
	}
	if in.DataMoverDataDownloads != nil {
		in, out := &in.DataMoverDataDownloads, &out.DataMoverDataDownloads
		*out = new(DataMoverDataDownloads)
		**out = **in
	}
	if in.FileSystemPodVolumeRestores != nil {
		in, out := &in.FileSystemPodVolumeRestores, &out.FileSystemPodVolumeRestores
		*out = new(FileSystemPodVolumeRestores)
		**out = **in
	}
	if in.QueueInfo != nil {
		in, out := &in.QueueInfo, &out.QueueInfo
		*out = new(QueueInfo)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonAdminRestoreStatus.
func (in *NonAdminRestoreStatus) DeepCopy() *NonAdminRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(NonAdminRestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueInfo) DeepCopyInto(out *QueueInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueInfo.
func (in *QueueInfo) DeepCopy() *QueueInfo {
	if in == nil {
		return nil
	}
	out := new(QueueInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceNonAdminBSL) DeepCopyInto(out *SourceNonAdminBSL) {
	*out = *in
	if in.RequestedSpec != nil {
		in, out := &in.RequestedSpec, &out.RequestedSpec
		*out = new(v1.BackupStorageLocationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceNonAdminBSL.
func (in *SourceNonAdminBSL) DeepCopy() *SourceNonAdminBSL {
	if in == nil {
		return nil
	}
	out := new(SourceNonAdminBSL)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VeleroBackup) DeepCopyInto(out *VeleroBackup) {
	*out = *in
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(v1.BackupSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(v1.BackupStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VeleroBackup.
func (in *VeleroBackup) DeepCopy() *VeleroBackup {
	if in == nil {
		return nil
	}
	out := new(VeleroBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VeleroBackupStorageLocation) DeepCopyInto(out *VeleroBackupStorageLocation) {
	*out = *in
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(v1.BackupStorageLocationStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VeleroBackupStorageLocation.
func (in *VeleroBackupStorageLocation) DeepCopy() *VeleroBackupStorageLocation {
	if in == nil {
		return nil
	}
	out := new(VeleroBackupStorageLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VeleroDeleteBackupRequest) DeepCopyInto(out *VeleroDeleteBackupRequest) {
	*out = *in
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(v1.DeleteBackupRequestStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VeleroDeleteBackupRequest.
func (in *VeleroDeleteBackupRequest) DeepCopy() *VeleroDeleteBackupRequest {
	if in == nil {
		return nil
	}
	out := new(VeleroDeleteBackupRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VeleroRestore) DeepCopyInto(out *VeleroRestore) {
	*out = *in
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(v1.RestoreStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VeleroRestore.
func (in *VeleroRestore) DeepCopy() *VeleroRestore {
	if in == nil {
		return nil
	}
	out := new(VeleroRestore)
	in.DeepCopyInto(out)
	return out
}
